/**
 * IPC channel names shared between the main process (handlers) and the
 * preload bridge. Centralized here so a typo can't silently break a call.
 */
export const Channels = {
  listDir: 'fs:listDir',
  getInfo: 'fs:getInfo',
  createFolder: 'fs:createFolder',
  createFile: 'fs:createFile',
  rename: 'fs:rename',
  copy: 'fs:copy',
  move: 'fs:move',
  duplicate: 'fs:duplicate',
  trash: 'fs:trash',
  open: 'fs:open',
  reveal: 'fs:reveal',
  quickAccess: 'fs:quickAccess',
  getHome: 'fs:getHome',
  appVersion: 'fs:appVersion',
  folderSize: 'fs:folderSize',
  search: 'fs:search',
  thumbnail: 'fs:thumbnail',
  watchSet: 'watch:set',
  dragStart: 'drag:start',
  prefsGet: 'prefs:get',
  prefsSet: 'prefs:set',
  tagsList: 'tags:list',
  tagsCreate: 'tags:create',
  tagsRename: 'tags:rename',
  tagsRemove: 'tags:remove',
  tagsAssign: 'tags:assign',
  tagsUnassign: 'tags:unassign',
  tagsForPaths: 'tags:forPaths',
  tagsFiles: 'tags:files',
  recentsList: 'recents:list',
  recentsRemove: 'recents:remove',
  recentsClear: 'recents:clear',
  viewsGet: 'views:get',
  viewsSet: 'views:set',
  drives: 'fs:drives',
  ejectDrive: 'fs:eject',
  openPrivacySettings: 'fs:openPrivacySettings',
  cloudConnect: 'cloud:connect',
  cloudConnectConfig: 'cloud:connectConfig',
  cloudListAccounts: 'cloud:listAccounts',
  cloudDisconnect: 'cloud:disconnect',
  aiStatus: 'ai:status',
  aiDownload: 'ai:download',
  aiCancelDownload: 'ai:cancelDownload',
  aiEmbed: 'ai:embed',
  aiEmbedImages: 'ai:embedImages',
  indexStart: 'index:start',
  indexPause: 'index:pause',
  indexClear: 'index:clear',
  indexStatus: 'index:status',
  indexAddExclude: 'index:addExclude',
  indexRemoveExclude: 'index:removeExclude',
  indexListExcludes: 'index:listExcludes',
  indexPickExcludes: 'index:pickExcludes',
  indexSetExcludeExtensions: 'index:setExcludeExtensions',
  indexSetInterval: 'index:setInterval',
  indexSetAmbient: 'index:setAmbient',
  indexSearch: 'index:search',
  indexSearchFile: 'index:searchFile',
  graphGet: 'graph:get',
  graphBuild: 'graph:build',
  graphStatus: 'graph:status',
  llmModels: 'llm:models',
  llmDownload: 'llm:download',
  llmCancelDownload: 'llm:cancelDownload',
  llmRemove: 'llm:remove',
  llmSpecs: 'llm:specs',
  chatSend: 'chat:send',
  chatStop: 'chat:stop',
  chatsList: 'chats:list',
  chatsMessages: 'chats:messages',
  chatsRename: 'chats:rename',
  chatsRemove: 'chats:remove',
} as const;

export type ChannelName = (typeof Channels)[keyof typeof Channels];

/** Main -> renderer push events (ipcRenderer.on, not invoke). */
export const Events = {
  /** A watched directory changed on disk; payload is the directory path. */
  dirChanged: 'fs:changed',
  /** AI model download/state progress; payload is an AiModelStatus. */
  aiModelProgress: 'ai:modelProgress',
  /** Background indexing progress; payload is an IndexProgress. */
  indexProgress: 'index:progress',
  /** Chat LLM download/state progress; payload is an LlmModelStatus. */
  llmModelProgress: 'llm:modelProgress',
  /** Streaming chat output; payload is a ChatStreamEvent. */
  chatStream: 'chat:stream',
  /** Knowledge-graph build progress; payload is a GraphProgress. */
  graphProgress: 'graph:progress',
} as const;
